## TODO: CREATE CLASS INVENTORY 

## TODO: SET CLASS INITIALISATION THAT GIVE CHARACTER BASIC INVENTORY

## TODO: METHODS FOR INVENTORY CLASS - GET INVENTORY, ADD TO INVENTORY, REMOVE FROM INVENTORY 
